Global:
  debug: false
  # device: cpu
  # use_gpu: false
  # use_mlu: false
  # use_xpu:
  # epoch_num: 500
  # log_smooth_window: 20
  # print_batch_step: 10
  # save_model_dir: ./output/ch_PP-OCR_V3_det/
  # save_epoch_step: 100
  # eval_batch_step:
  # - 0
  # - 400
  # cal_metric_during_train: false
  # pretrained_model: null
  # checkpoints: ./ckpts/detection.pth
  # save_inference_dir: null
  # use_visualdl: false
  # infer_img: doc/imgs_en/img_10.jpg
  # save_res_path: ./checkpoints/det_db/predicts_db.txt
  # distributed: false

  use_gpu: true
  use_xpu: false
  use_mlu: false
  use_tensorboard: false
  device: cpu
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/db_mv3/
  save_epoch_step: 1200
  # evaluation is run every 2000 iterations
  eval_batch_step: [ 0, 2000 ]
  cal_metric_during_train: False
  pretrained_model: ./ckpts/detection.pth
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Slim:
  Pruning:
    dummy_input: [ 1, 3, 960, 960 ]
    strict_out_nodes: true
    mark_unprunable: [ "node-847" ]
  Quantization: null

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.000001
  target_group_sparsity: 0.7
  pruning_steps: 1250
  pruning_periods: 10
  start_pruning_step: 1250

LRScheduler:
  name: CosineAnnealingLR
  warmup_epoch: 2

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./dataset/icdar2015/text_localization/
    label_file_list:
      - ./dataset/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - DetLabelEncode: null
      - IaaAugment:
          augmenter_args:
            - type: Fliplr
              args:
                p: 0.5
            - type: Affine
              args:
                rotate:
                  - -10
                  - 10
            - type: Resize
              args:
                size:
                  - 0.5
                  - 3
      - EastRandomCropData:
          size:
            - 960
            - 960
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
          order: hwc
      - ToCHWImage: null
      - KeepKeys:
          keep_keys:
            - image
            - threshold_map
            - threshold_mask
            - shrink_map
            - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./dataset/icdar2015/text_localization/
    label_file_list:
      - ./dataset/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - DetLabelEncode: null
      - DetResizeForTest: null
      - NormalizeImage:
          scale: 1./255.
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
          order: hwc
      - ToCHWImage: null
      - KeepKeys:
          keep_keys:
            - image
            - shape
            - polys
            - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 2
